### ISSUE TITLE
Tindie's custom fees in the EU

### ISSUE THREAD

**Issue by bendardenne** [dekuNukem/bob_cassette_rewinder#16]
Hello,

First, thanks for all the work! 

Unfortunately, Tindie's does not collect VAT at ordering, and so if you order from the EU you will (probably??) need to pay VAT yourself, along with hefty processing fees (I assume because of the new import rules that came in effect July 1st).

I don't know how easy it would be to find a platform which complies with EU VAT rules, but I think it would be good to mention this, here on GitHub and/or on Tindie's to avoid surprises for people like me who may not realize they are ordering from abroad :). Especially since a lot of people with Bobs are probably French. 

I had to pay 21€ to the Belgian post in VAT and processing fees to receive the chip :(

**Comment by dekuNukem** [comment]
Sorry to hear about the VAT fee, 21€ is a bit outreageous, that's almost the cost of this device!

Anyway, I have made some changes to the custom documents, and added more detailed decription of the product, hopefully it will make them happier.

**Comment by bendardenne** [comment]
If I understood correctly, there's no amount of description that can bypass this, unfortunately. The shop would need to charge VAT and then somehow pay it back to "the EU" (I guess the destination country?? no idea how this works). Some info here: https://www.bpost.be/en/shopping-outside-eu

What's outrageous is that 15€ flat processing fee that bpost charges. For people in other countries, it would be cheaper. Anyway, it's still a reasonable price given the amount I will save in the end, and the result is much better than if I soldered something myself, given my poor skills and the limited hardware I have at home.

**Comment by lechercheur123** [comment]
> What's outrageous is that 15€ flat processing fee that bpost charges. For people in other countries, it would be cheaper. 

In France, La Poste charges between 2 and 5€ of processing fees if you pay online, and 8€ if you pay directly the delivery man.
