### ISSUE TITLE
I get a banner from GitHub for this repo when I open my own repositories

### ISSUE THREAD

**Issue by ReagentX** [dekuNukem/bob_cassette_rewinder#24]
This issue isn't with this repo, I just found it amusing.

![IMG_0390](https://user-images.githubusercontent.com/1920666/172528277-e1ab30b3-dcbd-48de-b16b-d88dd768f0b1.png)

**Comment by dekuNukem** [comment]
That’s pretty funny😅 Wonder how much free exposure it got from this.

**Comment by dekuNukem** [comment]
Have you seen or interacted with this repo before, or is it the first time you heard of it 🤔?

**Comment by ReagentX** [comment]
I don't think I have, it doesn't look familiar to me.

**Comment by dekuNukem** [comment]
well not much I can do about it 😅
